# Generated by Django 4.0.3 on 2022-06-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoUrl', models.CharField(max_length=254)),
                ('price', models.CharField(max_length=254)),
                ('shortDescription', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Boutique',
        ),
    ]
