# Generated by Django 4.0.3 on 2022-07-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_produitfemme_produithomme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitenfant',
            name='enfant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitenfant',
            name='femme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitenfant',
            name='homme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitfemme',
            name='enfant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitfemme',
            name='femme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitfemme',
            name='homme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produithomme',
            name='enfant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produithomme',
            name='femme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produithomme',
            name='homme',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
