# Generated by Django 4.0.3 on 2022-07-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_produitenfant_enfant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitenfant',
            name='categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produitenfant',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produitenfant',
            name='price',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produitenfant',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produitfemme',
            name='categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produitfemme',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produitfemme',
            name='price',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produitfemme',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produithomme',
            name='categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produithomme',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produithomme',
            name='price',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produithomme',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
