export class Article{
    id !: number;
    photoTitle !: string;
    photoTexte !: string;
    title !: string;
    shortDescription !: string;
    questionOne !: string;
    answerOne !: string;
    questionTwo !: string;
    answerTwo !: string;
    questionThree !: string;
    answerThree !: string;
    questionFour !: string;
    answerFour !: string;
    questionFive !: string;
    answerFive !: string;
    questionSix !: string;
    answerSix !: string;
    questionSeven !: string;
    answerSeven !: string;
    questionEight !: string;
    answerEight !: string;
    questionNine !: string;
    answerNine !: string;
    questionTen !: string;
    answerTen !: string;
}