# Generated by Django 4.0.3 on 2022-07-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupeDeFrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('adversaire', models.CharField(max_length=25)),
                ('scrore', models.CharField(max_length=15)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CoupeDeLaLigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('adversaire', models.CharField(max_length=25)),
                ('scrore', models.CharField(max_length=15)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CoupeDesCoupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('adversaire', models.CharField(max_length=25)),
                ('scrore', models.CharField(max_length=5)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LigueUn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('victoire', models.CharField(max_length=3)),
                ('nul', models.CharField(max_length=3)),
                ('defaite', models.CharField(max_length=3)),
                ('point', models.CharField(max_length=3)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TropheesDesChampions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('adversaire', models.CharField(max_length=25)),
                ('scrore', models.CharField(max_length=5)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
    ]
