# Generated by Django 4.0.3 on 2022-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palmares', '0003_rename_scrore_coupedefrance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupedefrance',
            name='adversaire',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='coupedefrance',
            name='score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coupedelaligue',
            name='score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tropheesdeschampions',
            name='score',
            field=models.CharField(max_length=20),
        ),
    ]
