# Generated by Django 4.0.3 on 2022-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('firstName', models.CharField(blank=True, max_length=254, null=True)),
                ('lastName', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('mail', models.CharField(blank=True, max_length=254, null=True)),
                ('item', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
