# Generated by Django 4.0.3 on 2022-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressMail', models.CharField(max_length=254)),
                ('firstName', models.CharField(max_length=254)),
                ('lastName', models.CharField(max_length=254)),
            ],
        ),
    ]
