# Generated by Django 4.0.3 on 2022-08-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addressMail',
            new_name='address',
        ),
    ]
