# Generated by Django 4.0.3 on 2022-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0002_rename_photourl_article_phototexte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='AnswerFive',
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerFour',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerOne',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerThree',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerTwo',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionFive',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionFour',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionOne',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionThree',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionTwo',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
