# Generated by Django 4.0.3 on 2022-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0003_rename_text_article_answerfive_article_answerfour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='AnswerEight',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerNine',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerSeven',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerSix',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='AnswerTen',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionEight',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionNine',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionSeven',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionSix',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='QuestionTen',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
