# Generated by Django 4.0.3 on 2022-07-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0005_alter_article_answereight_alter_article_answerfive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='AnswerEight',
            new_name='answerEight',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerFive',
            new_name='answerFive',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerFour',
            new_name='answerFour',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerNine',
            new_name='answerNine',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerOne',
            new_name='answerOne',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerSeven',
            new_name='answerSeven',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerSix',
            new_name='answerSix',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerTen',
            new_name='answerTen',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerThree',
            new_name='answerThree',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='AnswerTwo',
            new_name='answerTwo',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionEight',
            new_name='questionEight',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionFive',
            new_name='questionFive',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionFour',
            new_name='questionFour',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionNine',
            new_name='questionNine',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionOne',
            new_name='questionOne',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionSeven',
            new_name='questionSeven',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionSix',
            new_name='questionSix',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionTen',
            new_name='questionTen',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionThree',
            new_name='questionThree',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='QuestionTwo',
            new_name='questionTwo',
        ),
    ]
