# Generated by Django 4.0.3 on 2022-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=254)),
                ('nationality', models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Attaquant',
        ),
        migrations.DeleteModel(
            name='Defenseur',
        ),
        migrations.DeleteModel(
            name='Gardien',
        ),
        migrations.DeleteModel(
            name='Milieu',
        ),
    ]
