# Generated by Django 4.0.3 on 2022-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0002_joueur_delete_attaquant_delete_defenseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defenseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=254)),
                ('nationality', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gardien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=254)),
                ('nationality', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Milieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('photoUrl', models.CharField(max_length=254)),
                ('nationality', models.CharField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Joueur',
            new_name='Attaquant',
        ),
    ]
