# Generated by Django 4.0.3 on 2022-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0003_defenseur_gardien_milieu_rename_joueur_attaquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardien',
            name='number',
            field=models.CharField(default='00', max_length=2),
            preserve_default=False,
        ),
    ]
