# Generated by Django 4.0.3 on 2022-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0004_gardien_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attaquant',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='defenseur',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='gardien',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='milieu',
            name='poste',
        ),
        migrations.AddField(
            model_name='attaquant',
            name='number',
            field=models.CharField(default='00', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defenseur',
            name='number',
            field=models.CharField(default='00', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milieu',
            name='number',
            field=models.CharField(default='00', max_length=2),
            preserve_default=False,
        ),
    ]
