# Generated by Django 4.0.3 on 2022-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0005_remove_attaquant_poste_remove_defenseur_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entete', models.CharField(max_length=254)),
                ('body', models.CharField(blank=True, max_length=254, null=True)),
                ('footer', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
