# Generated by Django 4.0.3 on 2022-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0006_fiche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fiche',
        ),
        migrations.AddField(
            model_name='attaquant',
            name='body',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attaquant',
            name='entete',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attaquant',
            name='footer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='defenseur',
            name='body',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='defenseur',
            name='entete',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='defenseur',
            name='footer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gardien',
            name='body',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gardien',
            name='entete',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gardien',
            name='footer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='milieu',
            name='body',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='milieu',
            name='entete',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='milieu',
            name='footer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
