# Generated by Django 4.0.3 on 2022-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0007_delete_fiche_attaquant_body_attaquant_entete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_created', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=2)),
                ('photoUrl', models.CharField(max_length=254)),
                ('nationality', models.CharField(max_length=254)),
                ('entete', models.CharField(blank=True, max_length=254, null=True)),
                ('body', models.CharField(blank=True, max_length=254, null=True)),
                ('footer', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
