# Generated by Django 4.0.3 on 2022-07-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0008_joueurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurs',
            name='poste',
            field=models.CharField(default='GB', max_length=50),
            preserve_default=False,
        ),
    ]
