# Generated by Django 4.0.3 on 2022-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0009_joueurs_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurs',
            name='photoUrlBis',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
