# Generated by Django 4.0.3 on 2022-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0011_alter_joueurs_photourlbis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueurs',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
