# Generated by Django 4.0.3 on 2022-08-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effectif', '0012_alter_joueurs_photourl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attaquant',
        ),
        migrations.DeleteModel(
            name='Defenseur',
        ),
        migrations.DeleteModel(
            name='Gardien',
        ),
        migrations.DeleteModel(
            name='Milieu',
        ),
    ]
